In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('us_equities_news_dataset.csv')

In [6]:
aapl_data = data[data['ticker'] == 'AAPL']

In [9]:
aapl_data[aapl_data['category'] == 'news']

,id,ticker,title,category,content,release_date,provider,url,article_id
49183,270698,AAPL,JPMorgan cautious ahead of Apple earnings,news,JPMorgan lifts its Apple AAPL 2 9 target f...,2020-01-28,Seeking Alpha,https://invst.ly/pnjv8,2068762
49184,270699,AAPL,FAANG s Fall but Get Some Wall Street Love,news,By Kim Khan \nInvesting com The FAANG stocks...,2020-01-28,Investing.com,https://www.investing.com/news/stock-market-ne...,2068765
49185,270700,AAPL,Wall Street tumbles as virus fuels economic worry,news,By Chuck Mikolajczak NEW YORK Reuters U S ...,2020-01-28,Reuters,https://www.investing.com/news/stock-market-ne...,2068311
49186,270701,AAPL,Earnings Watch Apple and AMD to take earnings...,news,Two of the best performing tech stocks of 2019...,2020-01-28,MarketWatch,https://invst.ly/pnlbs,2068906
49187,270702,AAPL,Day Ahead Top 3 Things to Watch for Jan 28,news,By Yasin Ebrahim and Kim Khan \n1 Apple Readi...,2020-01-28,Investing.com,https://www.investing.com/news/stock-market-ne...,2068907
...,...,...,...,...,...,...,...,...,...
62753,284268,AAPL,U S stocks slide ahead of ISM data Dow Jones...,news,Investing com U S stocks opened lower on Tu...,2013-11-05,Investing.com,https://www.investing.com/news/stock-market-ne...,254754
62754,284269,AAPL,U S futures rise although Fed uncertainty rem...,news,Investing com U S stock futures pointed to ...,2013-11-06,Investing.com,https://www.investing.com/news/stock-market-ne...,254811
62755,284270,AAPL,U S stocks open higher Fed tapering in focus...,news,Investing com U S stocks opened higher on W...,2013-11-06,Investing.com,https://www.investing.com/news/stock-market-ne...,254818
62756,284271,AAPL,U S futures edge higher ahead of nonfarm payr...,news,Investing com U S stock futures pointed to ...,2013-11-08,Investing.com,https://www.investing.com/news/stock-market-ne...,254932
62757,284272,AAPL,U S stocks open higher after payrolls data D...,news,Investing com U S stocks opened higher on F...,2013-11-08,Investing.com,https://www.investing.com/news/stock-market-ne...,254945

In [11]:
data.groupby('release_date').sum()

                    id  article_id
release_date
2008-10-02      227750         669
2008-10-03     1646462        2712
2008-10-06      851265        1428
2008-10-07      585155        1482
2008-10-08      320023         771
...                ...         ...
2020-02-09    24293654  7660828976
2020-02-10    31214464  7295214722
2020-02-11    31784527  6900486370
2020-02-12    18706240  4456955779
2020-02-13    17953142  2268072741

[3641 rows x 2 columns]